ktor {
    development = ${IS_DEV_ENV}
    testing = ${IS_TEST_ENV}
    production = ${IS_PROD_ENV}

    application {
        modules = [ com.alexh.ApplicationKt.setupModule, com.alexh.ApplicationKt.endpointModule ]
    }

    deployment {
        port = ${SERVER_PORT}
        host = ${SERVER_HOST}

        watch = [ classes, resources ]
        connectionGroupSize = 3
        workerGroupSize = 12
        callGroupSize = 300

        shutdownGracePeriod = 2000
        shutdownTimeout = 3000

        maxInitialLineLength = 2048
        maxHeaderSize = 1024
        maxChunkSize = 42
    }

    security {
        ssl {
            keyStore = ${KEYSTORE_FILE_PATH}
            keyAlias = ${KEY_ALIAS}
            keyStorePassword = ${KEY_STORE_PASSWORD}
            privateKeyPassword = ${PRIVATE_KEY_PASSWORD}
        }
    }
}

postgres {
    url = ${DB_URL}
    username = ${DB_OWNER}
    password = ${DB_PASS}
}
